# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zI1HRsrHz4Kpr_ZIjnJqAZiTSA_ouneC
"""

# -*- coding: utf-8 -*-
"""
Full drop-in: 2R RRT demo with
- wrap-aware planning on S1 x S1
- wrap-aware plotting
- periodic 3x3 torus C-space tiling
- narrow-passage-friendly planner defaults
"""

import numpy as np
import matplotlib
matplotlib.use('module://matplotlib_inline.backend_inline')
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
from matplotlib.collections import LineCollection
from ipywidgets import interact, Button, Output, HBox, fixed
from IPython.display import display, clear_output
import random, time

# ── Robot parameters ──────────────────────────────────────────────────────────
L1, L2 = 1.0, 1.0
START_Q = np.array([0.0, 0.0])
GOAL_Q = np.array([np.pi / 2, 0.0])


# ── Helpers ──────────────────────────────────────────────────────────────────
def wrap_angle(a):
    return (a + np.pi) % (2 * np.pi) - np.pi


def angle_dist(a, b):
    d = wrap_angle(a - b)
    return np.linalg.norm(d)


def angle_dist_batch(nodes_arr, target):
    d = wrap_angle(nodes_arr - target)
    return np.linalg.norm(d, axis=1)


def split_wrapped_segment(p1, p2, threshold=np.pi):
    raw_jump = np.abs(p2 - p1)
    if np.any(raw_jump > threshold):
        return []
    return [[p1, p2]]


def get_arm_coords(t1, t2):
    x1, y1 = L1 * np.cos(t1), L1 * np.sin(t1)
    x2, y2 = x1 + L2 * np.cos(t1 + t2), y1 + L2 * np.sin(t1 + t2)
    return [(0, x1, x2), (0, y1, y2)]


def line_rect_intersect(p1, p2, rect):
    xmin, xmax = rect['xmin'], rect['xmax']
    ymin, ymax = rect['ymin'], rect['ymax']

    for p in (p1, p2):
        if xmin <= p[0] <= xmax and ymin <= p[1] <= ymax:
            return True

    dx, dy = p2[0] - p1[0], p2[1] - p1[1]
    p_ = [-dx, dx, -dy, dy]
    q_ = [p1[0] - xmin, xmax - p1[0], p1[1] - ymin, ymax - p1[1]]

    u1, u2 = 0.0, 1.0
    for i in range(4):
        if p_[i] == 0:
            if q_[i] < 0:
                return False
        else:
            t = q_[i] / p_[i]
            if p_[i] < 0:
                u1 = max(u1, t)
            else:
                u2 = min(u2, t)
    return u1 <= u2


def check_collision_single(t1, t2, rect, buffer=0.05):
    br = {k: rect[k] + s * buffer for k, s in zip(('xmin', 'xmax', 'ymin', 'ymax'), (-1, 1, -1, 1))}
    x1, y1 = L1 * np.cos(t1), L1 * np.sin(t1)
    x2, y2 = x1 + L2 * np.cos(t1 + t2), y1 + L2 * np.sin(t1 + t2)

    return (
        line_rect_intersect((0, 0), (x1, y1), br)
        or line_rect_intersect((x1, y1), (x2, y2), br)
    )


def build_cspace_grid(rect, N=500, buffer=0.05):
    t = np.linspace(-np.pi, np.pi, N)
    C = np.zeros((N, N))
    for i, t1 in enumerate(t):
        for j, t2 in enumerate(t):
            C[j, i] = check_collision_single(t1, t2, rect, buffer)
    return C


def draw_periodic_cspace(ax, C, alpha=0.30):
    shifts = [-2 * np.pi, 0, 2 * np.pi]
    for dx in shifts:
        for dy in shifts:
            ax.imshow(
                C,
                origin='lower',
                extent=[-np.pi + dx, np.pi + dx, -np.pi + dy, np.pi + dy],
                cmap='Greys',
                alpha=alpha,
            )
    ax.set_xlim(-np.pi, np.pi)
    ax.set_ylim(-np.pi, np.pi)


# ── RRT ──────────────────────────────────────────────────────────────────────
class RRT:
    def __init__(self, start, goal, rect, expand_dist=0.03, goal_rate=0.1, max_iter=12000, edge_check_steps=20):
        self.start = np.array(start)
        self.goal = np.array(goal)
        self.rect = rect
        self.expand_dist = expand_dist
        self.goal_rate = goal_rate
        self.max_iter = max_iter
        self.edge_steps = edge_check_steps
        self.tree = [self.start]
        self.parents = [None]

    def _edge_in_collision(self, n1, n2):
        diff = wrap_angle(n2 - n1)
        for t in np.linspace(0, 1, self.edge_steps):
            q = wrap_angle(n1 + t * diff)
            if check_collision_single(*q, self.rect):
                return True
        return False

    def plan(self):
        nodes = np.array(self.tree)
        for _ in range(self.max_iter):
            rnd = self.goal if random.random() < self.goal_rate else np.random.uniform(-np.pi, np.pi, 2)
            near_idx = int(np.argmin(angle_dist_batch(nodes, rnd)))
            near = self.tree[near_idx]

            diff = wrap_angle(rnd - near)
            dist = np.linalg.norm(diff)
            if dist < 1e-9:
                continue

            if dist > self.expand_dist:
                new = near + (diff / dist) * self.expand_dist
            else:
                new = rnd.copy()

            new = wrap_angle(new)

            if check_collision_single(*new, self.rect):
                continue
            if self._edge_in_collision(near, new):
                continue

            self.tree.append(new)
            self.parents.append(near_idx)
            nodes = np.vstack([nodes, new])

            if angle_dist(new, self.goal) < self.expand_dist:
                path, curr = [], len(self.tree) - 1
                while curr is not None:
                    path.append(self.tree[curr])
                    curr = self.parents[curr]
                return np.array(path[::-1])
        return None


# ── UI state ─────────────────────────────────────────────────────────────────
state = {
    '_fig': None,
    '_arm_line': None,
    '_arm_dots': None,
    '_cur_dot2': None,
    'x': 0.9,
    'y': 0.2,
    'size': 0.2,
    'path': None,
    'tree': None,
    'parents': None,
    '_cspace': None,
    '_obs_key': None,
}

out = Output()
run_btn = Button(description='Run RRT Planner', button_style='success')
anim_btn = Button(description='Animate Path', button_style='info')


def _no_go():
    h = 0.5 * state['size']
    return {
        'xmin': state['x'] - h,
        'xmax': state['x'] + h,
        'ymin': state['y'] - h,
        'ymax': state['y'] + h,
    }


def _get_cspace(no_go):
    key = tuple(round(no_go[k], 4) for k in ('xmin', 'xmax', 'ymin', 'ymax'))
    if state['_obs_key'] != key:
        state['_cspace'] = build_cspace_grid(no_go)
        state['_obs_key'] = key
    return state['_cspace']


def full_redraw(current_q=None):
    no_go = _no_go()
    C = _get_cspace(no_go)
    q_now = current_q if current_q is not None else (state['path'][0] if state['path'] is not None else START_Q)

    with out:
        clear_output(wait=True)
        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))

        # Workspace
        ax1.set_xlim(-2.2, 2.2)
        ax1.set_ylim(-2.2, 2.2)
        ax1.set_aspect('equal')
        ax1.set_title('Workspace')
        ax1.add_patch(Rectangle((no_go['xmin'], no_go['ymin']), state['size'], state['size'], color='red', alpha=0.4))

        px, py = get_arm_coords(*q_now)
        ax1.plot(px, py, 'k-', lw=4)
        ax1.scatter(list(px), list(py), color='black')

        sx, sy = get_arm_coords(*START_Q)
        gx, gy = get_arm_coords(*GOAL_Q)
        ax1.plot(sx, sy, 'g--', lw=2)
        ax1.plot(gx, gy, 'b--', lw=2)

        # C-space
        ax2.set_title('C-Space (Periodic Torus)')
        draw_periodic_cspace(ax2, C)

        tree, parents = state['tree'], state['parents']
        if tree is not None and len(tree) > 1:
            segs = []
            for i in range(1, len(tree)):
                if parents[i] is None:
                    continue
                p1 = wrap_angle(np.array(tree[parents[i]]))
                p2 = wrap_angle(np.array(tree[i]))
                segs.extend(split_wrapped_segment(p1, p2))
            ax2.add_collection(LineCollection(segs, colors='steelblue', linewidths=0.6, alpha=0.5))

        if state['path'] is not None:
            wrapped_path = np.array([wrap_angle(q) for q in state['path']])
            ax2.plot(wrapped_path[:, 0], wrapped_path[:, 1], 'r-', lw=2)

        ax2.scatter(*wrap_angle(START_Q), color='green', s=100)
        ax2.scatter(*wrap_angle(GOAL_Q), color='blue', s=100)
        ax2.scatter(*wrap_angle(q_now), color='orange', s=80)

        plt.tight_layout()

        # Cache lightweight animation handles
        state['_fig'] = fig
        state['_arm_line'] = ax1.lines[0]
        state['_arm_dots'] = ax1.collections[0]
        state['_cur_dot2'] = ax2.collections[-1]

        plt.show()


def update_view(x_pos, y_pos, size, path=None):
    state.update({'x': x_pos, 'y': y_pos, 'size': size})
    full_redraw()


def on_run_clicked(_):
    planner = RRT(START_Q, GOAL_Q, _no_go())
    state['path'] = planner.plan()
    state['tree'] = list(planner.tree)
    state['parents'] = list(planner.parents)
    full_redraw()


def _update_frame(q):
    """Lightweight animation update: mutate only moving artists."""
    px, py = get_arm_coords(*q)

    state['_arm_line'].set_xdata(list(px))
    state['_arm_line'].set_ydata(list(py))
    state['_arm_dots'].set_offsets(np.column_stack([list(px), list(py)]))

    q_wrap = wrap_angle(q)
    state['_cur_dot2'].set_offsets([[q_wrap[0], q_wrap[1]]])

    with out:
        clear_output(wait=True)
        display(state['_fig'])


def on_anim_clicked(_):
    if state['path'] is None or state['_fig'] is None:
        return
    for q in state['path']:
        _update_frame(q)
        time.sleep(0.05)


run_btn.on_click(on_run_clicked)
anim_btn.on_click(on_anim_clicked)

interact(
    update_view,
    x_pos=(-1.5, 1.5, 0.1),
    y_pos=(-1.5, 1.5, 0.1),
    size=(0.1, 1.0, 0.1),
    path=fixed(None),
)

display(HBox([run_btn, anim_btn]), out)